version: '3.8'

services:
  # 1. La Base de Datos (Imagen oficial)
  mongodb:
    image: mongo:latest
    container_name: univy_db
    # Ya NO exponemos el puerto 27017 al host.
    # MongoDB solo es accesible desde la red interna.
    volumes:
      - mongo_data:/data/db
    networks:
      - backend_internal
    restart: unless-stopped

  # 2. Tu Backend Node.js
  backend:
    # Sustituye "tu_usuario" por tu nombre real de Docker Hub: g5_univy
    image: bictorp/backend-ea:v1.4 
    container_name: univy_backend
    ports:
      - "1337:1337" # Mapeamos el puerto 1337 que usas en server.ts
    depends_on:
      - mongodb
    env_file:
      # Carga automáticamente las variables de tu .env
      - ./EA_BACKEND_G5/.env 
    networks:
      - backend_internal  # Para hablar con MongoDB
      - frontend_net      # Para que web/backoffice lleguen al backend
    restart: unless-stopped

  # 3. La WebApp (React/Vite)
  web:
    image: bictorp/web-ea:v1
    container_name: univy_web
    ports:
      - "80:80" # Tu web se verá en http://localhost  
    depends_on:
      - backend
    networks:
      - frontend_net
    restart: unless-stopped

  # 4. El Backoffice (Angular)
  backoffice:
    image: bictorp/backoffice-ea:v1.2
    container_name: univy_backoffice
    ports:
      - "9000:80" # Tu backoffice se verá en http://localhost:9000
    depends_on:
      - backend
    networks:
      - frontend_net
    restart: unless-stopped

# Declaramos el volumen para que Mongo no pierda datos si se apaga  
volumes:
  mongo_data:

# Declaramos las redes
networks:
  backend_internal:
    driver: bridge
    internal: true   # <-- Clave: esta red NO tiene salida a internet ni al host
  frontend_net:
    driver: bridge